ssh_user: root
ssh_key: ~/.ssh/id_rsa

proxmox_host: 192.168.12.20

masters:
  - name: master-1
    ip: 10.100.0.100
  - name: master-2
    ip: 10.100.0.101
  - name: master-3
    ip: 10.100.0.102

workers:
  - name: worker-1
    ip: 10.100.0.110
  - name: worker-2
    ip: 10.100.0.111
  - name: worker-3
    ip: 10.100.0.112

gateway: 10.100.0.1

