apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mattermost-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mattermost/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mattermost-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mattermost/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mattermost-logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mattermost/logs"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mattermost-plugins
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mattermost/plugins"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mattermost-client-plugins
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mattermost/client-plugins"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mattermost-bleve-indexes
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mattermost/bleve-indexes"

